"""
AIDSTL Project — Utils Package
===============================
Utility modules for spatial analysis and spectral index computation.
"""

from app.utils.spatial import (
    UTM_EPSG,
    WATERWAY_META,
    WGS84_EPSG,
    assign_nearest_gauge,
    buffer_segment,
    compute_channel_width,
    compute_sinuosity,
    geojson_to_geodataframe,
    geojson_to_response,
    get_waterway_meta,
    interpolate_gauge_to_segment,
    make_segment_id,
    parse_segment_id,
    segment_bounding_box,
    segment_river,
)
from app.utils.spectral import (
    FEATURE_NAMES,
    SENTINEL2_BANDS,
    aggregate_segment_features,
    build_feature_vector,
    compute_all_indices,
    compute_awei,
    compute_awei_nsh,
    compute_awei_sh,
    compute_evi,
    compute_mndwi,
    compute_ndsi,
    compute_ndvi,
    compute_ndwi,
    compute_stumpf_ratio,
    compute_stumpf_ratio_brg,
    compute_turbidity,
    estimate_depth_from_stumpf,
    normalize_features,
    water_mask_from_mndwi,
)

__all__ = [
    # spatial
    "segment_river",
    "interpolate_gauge_to_segment",
    "compute_channel_width",
    "compute_sinuosity",
    "geojson_to_response",
    "geojson_to_geodataframe",
    "buffer_segment",
    "segment_bounding_box",
    "assign_nearest_gauge",
    "make_segment_id",
    "parse_segment_id",
    "get_waterway_meta",
    "WATERWAY_META",
    "WGS84_EPSG",
    "UTM_EPSG",
    # spectral
    "compute_mndwi",
    "compute_ndwi",
    "compute_awei",
    "compute_awei_sh",
    "compute_awei_nsh",
    "compute_stumpf_ratio",
    "compute_stumpf_ratio_brg",
    "compute_turbidity",
    "compute_ndsi",
    "compute_ndvi",
    "compute_evi",
    "build_feature_vector",
    "normalize_features",
    "compute_all_indices",
    "water_mask_from_mndwi",
    "estimate_depth_from_stumpf",
    "aggregate_segment_features",
    "FEATURE_NAMES",
    "SENTINEL2_BANDS",
]
